### ISSUE TITLE
[BUG REPORT] armor bar with glint not rendering

### ISSUE THREAD

**Issue by itsMarkiS** [A5b84/armor-chroma-fabric#14] opened 2022-11-28 05:53 UTC
in the latest update for 1.19.2 the armor bar only renders when the glint option is off, if its turned on, everything is rendered fully black, except for the glint effect which still applies

**Comment by itsMarkiS** [comment] 2023-01-06 21:35
today i got a crash

Stacktrace:
	at nukeduck.armorchroma.config.Util.getModid(Util.java:36)
	at nukeduck.armorchroma.config.IconData.getIcon(IconData.java:41)
	at nukeduck.armorchroma.GuiArmor.drawPartialRow(GuiArmor.java:133)
	at nukeduck.armorchroma.GuiArmor.drawPiece(GuiArmor.java:125)
	at nukeduck.armorchroma.GuiArmor.draw(GuiArmor.java:73)
	at net.minecraft.class_329.handler$zfm000$renderArmor(class_329.java:4995)
	at net.minecraft.class_329.method_1760(class_329.java:1059)
	at net.minecraft.class_329.method_1753(class_329.java:241)

**Comment by A5b84** [comment] 2023-01-07 18:04
I couldn't reproduce either issues but the first one sounds like an incompatibility, can you send your mod list (the one at the top of logs)?

And what version of Minecraft/the mod were you using when it crashed? (v1.2.3 doesn't work in 1.19.3)

**Comment by eunsoule** [comment] 2023-01-17 05:47
![image](https://user-images.githubusercontent.com/29917385/212819517-f959e697-ce14-43c9-93ba-6b43a9a777f8.png)
![image](https://user-images.githubusercontent.com/29917385/212819537-63c0cb2f-4c0c-40b1-9163-9116fcf56c9b.png)

Happening to me as well.

![image](https://user-images.githubusercontent.com/29917385/212819587-9274ee72-b983-4f43-a564-ff0ff0d97db5.png)

**Comment by A5b84** [comment] 2023-01-17 16:57
Can you send your logs / mod list?

**Comment by eunsoule** [comment] 2023-01-17 16:59
```
01/17/2023  14:29           129,183 armorchroma-1.2.4.jar
01/14/2023  19:01            91,442 BetterControls-Fabric-1.19.3+v1.2.4.jar
01/14/2023  19:02         6,580,158 caxton-0.2.1.jar
01/17/2023  13:41         1,143,110 cloth-config-9.0.94-fabric.jar
12/24/2022  15:08         1,036,725 continuity-2.0.2+1.19.3-build.2.jar
01/17/2023  14:24           133,932 exordium-fabric-1.0.3-mc1.19.3.jar
01/14/2023  19:02           118,628 indium-1.0.12+mc1.19.3.jar
01/14/2023  19:02            14,531 lazydfu-0.1.3.jar
01/14/2023  19:02           555,778 lithium-fabric-mc1.19.3-0.10.4.jar
01/14/2023  19:03           514,974 malilib-fabric-1.19.3-0.14.0.jar
01/14/2023  19:03           328,900 minihud-fabric-1.19.3-0.25.0.jar
01/14/2023  19:03           637,090 modmenu-5.0.2.jar
01/14/2023  19:04            11,223 morechathistory-1.19.1-1.1.1.jar
01/14/2023  19:04           270,470 ok_zoomer-5.0.0-beta.10+1.19.3.jar
01/14/2023  19:05         1,657,429 qfapi-5.0.0-alpha.9_qsl-4.0.0-beta.5_fapi-0.72.0_mc-1.19.3.jar
01/14/2023  19:05           715,490 sodium-fabric-mc1.19.3-0.4.8+build.22.jar
01/16/2023  16:43           127,465 starlight-1.1.1+fabric.ae22326.jar
01/15/2023  17:50         5,712,972 worldedit-mod-7.2.13.jar
01/14/2023  19:05           564,257 WorldEditCUI-1.19.3+01.jar
```

**Comment by A5b84** [comment] 2023-01-17 17:11
Thanks, I'll take a better look when I have some time

**Comment by GitNeub** [comment] 2023-02-20 15:35
Guys it's being caused because of Exordium, which doesn't change much and you can replace some of its functions with fpsreducer

**Comment by A5b84** [comment] 2024-12-21 16:26
I'll close this now considering it may not even happen anymore, feel free to reopen if the issue still happens in 1.21.4 or later

**Closed as completed by A5b84** 2024-12-21 16:26 UTC
Labels: bug
