### ISSUE TITLE
armor chroma clashing with appleskin

### ISSUE THREAD

**Issue by ProxtosScorn** [A5b84/armor-chroma-fabric#27] opened 2024-04-26 01:57 UTC
when using appleskin 2.5.1 with armor chroma 1.2.6 on 1.20.4, the "show hunger restored from held food" option of appleskin breaks, making the hunger icons flash transparent

**Comment by A5b84** [comment] 2024-06-02 23:03
Couldn't reproduce the issue in either 1.20.1 or 1.20.6 (I haven't tried 1.20.4) so this sounds like it could be caused by another mod, but let me know if the issue still happens in 1.20.6 with the latest version of armor chroma

**Comment by A5b84** [comment] 2024-11-18 23:23
Still couldn't reproduce in the soon-to-be-released 1.21.3 version so I'll close this and assume the issue comes from another mod

**Closed as not planned by A5b84** 2024-11-18 23:23 UTC
Labels: bug
